# pull official base image
FROM node:10 AS builder

# set working directory
WORKDIR /app


# install app dependencies
#copies package.json and package-lock.json to Docker environment
COPY package.json ./

# Installs all node packages
RUN npm install


# Copies everything over to Docker environment
COPY . /app
RUN npm run build


#Stage 2
#######################################
FROM arm32v7/nginx/nginx:1.21.3-alpine

RUN mkdir /home/videos && touch /home/videos/testfile.html
COPY ./src-docker/nginx.conf /etc/nginx/nginx.conf
COPY ./src-docker/default.conf /etc/nginx/conf.d/default.conf
# Copies static resources from builder stage
COPY --from=builder /app/build /usr/share/nginx/html