# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      newVersion:
        description: 'New package.json version'     
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        #with:
          # The branch, tag or SHA to checkout. When checking out the repository that
          # triggered a workflow, this defaults to the reference or SHA for that event.
          # Otherwise, uses the default branch.
          #ref: 'master'
          
      - name: Read package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version

      - name: Show version number
        run: echo "Version is ${{ steps.package-node-version.outputs.version }}"
        
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ferpinan/video-tree:latest, ferpinan/video-tree:${{ steps.package-node-version.outputs.version }}
      -
        name: Build and push armv7
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile-armv7
          tags: ferpinan/video-tree:${{ steps.package-node-version.outputs.version }}-armv7
